### ISSUE TITLE
Split django settings.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#171]

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#183](https://github.com/proofit404/cruftbot/issues/183) is still not solved.

**Comment by 0pdd** [comment]
@proofit404 7 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 8 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 15 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 16 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#190](https://github.com/proofit404/cruftbot/issues/190).

**Comment by 0pdd** [comment]
@proofit404 15 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190).

**Comment by 0pdd** [comment]
@proofit404 14 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190).

**Comment by 0pdd** [comment]
@proofit404 13 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190).

**Comment by 0pdd** [comment]
@proofit404 12 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#228](https://github.com/proofit404/cruftbot/issues/228).

**Comment by 0pdd** [comment]
@proofit404 11 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#187](https://github.com/proofit404/cruftbot/issues/187), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#228](https://github.com/proofit404/cruftbot/issues/228).

**Comment by 0pdd** [comment]
@proofit404 10 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#228](https://github.com/proofit404/cruftbot/issues/228).

**Comment by 0pdd** [comment]
@proofit404 9 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228).

**Comment by 0pdd** [comment]
@proofit404 8 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#224](https://github.com/proofit404/cruftbot/issues/224), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228).

**Comment by 0pdd** [comment]
@proofit404 7 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#230](https://github.com/proofit404/cruftbot/issues/230) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#224](https://github.com/proofit404/cruftbot/issues/224), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#231](https://github.com/proofit404/cruftbot/issues/231).

**Comment by proofit404** [comment]
As of #231 we'll no longer use [django-split-settings](https://github.com/sobolevn/django-split-settings) package due to its technical limitations.

**Comment by 0pdd** [comment]
@proofit404 6 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#224](https://github.com/proofit404/cruftbot/issues/224), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231).

**Comment by 0pdd** [comment]
@proofit404 5 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#205](https://github.com/proofit404/cruftbot/issues/205), [#223](https://github.com/proofit404/cruftbot/issues/223), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#222](https://github.com/proofit404/cruftbot/issues/222), [#224](https://github.com/proofit404/cruftbot/issues/224), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231).

**Comment by 0pdd** [comment]
@proofit404 5 puzzles [#183](https://github.com/proofit404/cruftbot/issues/183), [#223](https://github.com/proofit404/cruftbot/issues/223), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#344](https://github.com/proofit404/cruftbot/issues/344) are still not solved; solved: [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#224](https://github.com/proofit404/cruftbot/issues/224), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231).

**Comment by 0pdd** [comment]
@proofit404 8 puzzles [#223](https://github.com/proofit404/cruftbot/issues/223), [#226](https://github.com/proofit404/cruftbot/issues/226), [#344](https://github.com/proofit404/cruftbot/issues/344), [#370](https://github.com/proofit404/cruftbot/issues/370), [#371](https://github.com/proofit404/cruftbot/issues/371), [#372](https://github.com/proofit404/cruftbot/issues/372), [#373](https://github.com/proofit404/cruftbot/issues/373), [#374](https://github.com/proofit404/cruftbot/issues/374) are still not solved; solved: [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231).

**Comment by 0pdd** [comment]
@proofit404 7 puzzles [#226](https://github.com/proofit404/cruftbot/issues/226), [#344](https://github.com/proofit404/cruftbot/issues/344), [#370](https://github.com/proofit404/cruftbot/issues/370), [#371](https://github.com/proofit404/cruftbot/issues/371), [#372](https://github.com/proofit404/cruftbot/issues/372), [#373](https://github.com/proofit404/cruftbot/issues/373), [#374](https://github.com/proofit404/cruftbot/issues/374) are still not solved; solved: [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231).

**Comment by 0pdd** [comment]
@proofit404 6 puzzles [#344](https://github.com/proofit404/cruftbot/issues/344), [#370](https://github.com/proofit404/cruftbot/issues/370), [#371](https://github.com/proofit404/cruftbot/issues/371), [#372](https://github.com/proofit404/cruftbot/issues/372), [#373](https://github.com/proofit404/cruftbot/issues/373), [#374](https://github.com/proofit404/cruftbot/issues/374) are still not solved; solved: [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231).

**Comment by 0pdd** [comment]
@proofit404 5 puzzles [#344](https://github.com/proofit404/cruftbot/issues/344), [#371](https://github.com/proofit404/cruftbot/issues/371), [#372](https://github.com/proofit404/cruftbot/issues/372), [#373](https://github.com/proofit404/cruftbot/issues/373), [#374](https://github.com/proofit404/cruftbot/issues/374) are still not solved; solved: [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231), [#370](https://github.com/proofit404/cruftbot/issues/370).

**Comment by 0pdd** [comment]
@proofit404 4 puzzles [#344](https://github.com/proofit404/cruftbot/issues/344), [#372](https://github.com/proofit404/cruftbot/issues/372), [#373](https://github.com/proofit404/cruftbot/issues/373), [#374](https://github.com/proofit404/cruftbot/issues/374) are still not solved; solved: [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231), [#370](https://github.com/proofit404/cruftbot/issues/370), [#371](https://github.com/proofit404/cruftbot/issues/371).

**Comment by 0pdd** [comment]
@proofit404 3 puzzles [#344](https://github.com/proofit404/cruftbot/issues/344), [#372](https://github.com/proofit404/cruftbot/issues/372), [#374](https://github.com/proofit404/cruftbot/issues/374) are still not solved; solved: [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231), [#370](https://github.com/proofit404/cruftbot/issues/370), [#371](https://github.com/proofit404/cruftbot/issues/371), [#373](https://github.com/proofit404/cruftbot/issues/373).

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#344](https://github.com/proofit404/cruftbot/issues/344), [#374](https://github.com/proofit404/cruftbot/issues/374) are still not solved; solved: [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231), [#370](https://github.com/proofit404/cruftbot/issues/370), [#371](https://github.com/proofit404/cruftbot/issues/371), [#372](https://github.com/proofit404/cruftbot/issues/372), [#373](https://github.com/proofit404/cruftbot/issues/373).

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#344](https://github.com/proofit404/cruftbot/issues/344) is still not solved; solved: [#183](https://github.com/proofit404/cruftbot/issues/183), [#185](https://github.com/proofit404/cruftbot/issues/185), [#186](https://github.com/proofit404/cruftbot/issues/186), [#187](https://github.com/proofit404/cruftbot/issues/187), [#188](https://github.com/proofit404/cruftbot/issues/188), [#189](https://github.com/proofit404/cruftbot/issues/189), [#190](https://github.com/proofit404/cruftbot/issues/190), [#205](https://github.com/proofit404/cruftbot/issues/205), [#222](https://github.com/proofit404/cruftbot/issues/222), [#223](https://github.com/proofit404/cruftbot/issues/223), [#224](https://github.com/proofit404/cruftbot/issues/224), [#225](https://github.com/proofit404/cruftbot/issues/225), [#226](https://github.com/proofit404/cruftbot/issues/226), [#227](https://github.com/proofit404/cruftbot/issues/227), [#228](https://github.com/proofit404/cruftbot/issues/228), [#230](https://github.com/proofit404/cruftbot/issues/230), [#231](https://github.com/proofit404/cruftbot/issues/231), [#370](https://github.com/proofit404/cruftbot/issues/370), [#371](https://github.com/proofit404/cruftbot/issues/371), [#372](https://github.com/proofit404/cruftbot/issues/372), [#373](https://github.com/proofit404/cruftbot/issues/373), [#374](https://github.com/proofit404/cruftbot/issues/374).
