### ISSUE TITLE
Remark linter does not work on local machine.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#208]
See https://github.com/proofit404/cruftbot/pull/194#issuecomment-797311261

**Comment by proofit404** [comment]
Turns out our docker image will not have default user.

In the mean time our local directory will be mount with UID and GID or our local user.

If user with matching UID does not exists inside docker image even root user will see EACCESS.

Solution to this situation should be straight forward - create user in docker container.

UID and GID will be specified using ARGS through compose file.

If you have UID different from default (1000 on debian) you could use override file to correct those values according to your system.

See https://docs.docker.com/compose/extends/#example-use-case

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#212](https://github.com/proofit404/cruftbot/issues/212) is still not solved.

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#214](https://github.com/proofit404/cruftbot/issues/214) is still not solved; solved: [#212](https://github.com/proofit404/cruftbot/issues/212).

**Comment by 0pdd** [comment]
@proofit404 all 2 puzzles are solved here: [#212](https://github.com/proofit404/cruftbot/issues/212), [#214](https://github.com/proofit404/cruftbot/issues/214).
