### ISSUE TITLE
Dockerfile:49: Poetry directory...

### ISSUE THREAD

**Issue by 0pdd** [proofit404/cruftbot#214]
The puzzle `212-0fbe2616` from #212 has to be resolved: 

https://github.com/proofit404/cruftbot/blob/063cc537104b14509e8112b8ad2d26deec6b5232/Dockerfile#L49-L49

The puzzle was created by @proofit404 on 18-Mar-21. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by proofit404** [comment]
```
Creating cruftbot_app_run ... done
==> Installing python dependencies…
Creating virtualenv cruftbot-9TtSrW0h-py3.9 in /home/app/.cache/pypoetry/virtualenvs
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--symlinks | --copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: argument dest: the destination . is not write-able at /home/app/.cache
```
Looks like version of virtual environment vendored with poetry does not create target directory.

**Comment by 0pdd** [comment]
The puzzle `212-0fbe2616` has disappeared from the source code, that's why I closed this issue.
