### ISSUE TITLE
development.py:13-16: Reuse components definition from...

### ISSUE THREAD

**Issue by 0pdd** [proofit404/cruftbot#230]
The puzzle `183-23a1a034` from #183 has to be resolved: 

https://github.com/proofit404/cruftbot/blob/476d65e1a37b7535a7367ecf10c951f7e494fd96/cruftbot/settings/development.py#L13-L16

The puzzle was created by Artem Malyshev on 18-Mar-21. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by proofit404** [comment]
See [wemake-django-template](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/__init__.py#L32) for example.

**Comment by 0pdd** [comment]
The puzzle `183-23a1a034` has disappeared from the source code, that's why I closed this issue.
