### ISSUE TITLE
node_assets.py:5-9: Components can not import each other....

### ISSUE THREAD

**Issue by 0pdd** [proofit404/cruftbot#231]
The puzzle `183-440b064e` from #183 has to be resolved: 

https://github.com/proofit404/cruftbot/blob/476d65e1a37b7535a7367ecf10c951f7e494fd96/cruftbot/settings/components/node_assets.py#L5-L9

The puzzle was created by Artem Malyshev on 18-Mar-21. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by proofit404** [comment]
See https://github.com/sobolevn/django-split-settings/issues/286 for more info.

**Comment by 0pdd** [comment]
The puzzle `183-440b064e` has disappeared from the source code, that's why I closed this issue.
