### ISSUE TITLE
GitHub actions does not set GITHUB_TOKEN in pull requests.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#283]
Danger code review does not work because of that.

See #92

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#287](https://github.com/proofit404/cruftbot/issues/287) is still not solved.

**Comment by 0pdd** [comment]
@proofit404 the only puzzle [#287](https://github.com/proofit404/cruftbot/issues/287) is solved here.

**Comment by proofit404** [comment]
Danger can't leave comments on pull requests made by dependabot.
