### ISSUE TITLE
Setup eslint.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#355]
We need configure eslint to use recommended rule set.

In addition it should be aware of environment in which code will be executed. External plugin looks like a good option to do that. See https://github.com/amilajack/eslint-plugin-compat for more details.

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#442](https://github.com/proofit404/cruftbot/issues/442) is still not solved.

**Comment by 0pdd** [comment]
@proofit404 the only puzzle [#442](https://github.com/proofit404/cruftbot/issues/442) is solved here.
