### ISSUE TITLE
Setup stylelint.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#356]
We need to configure stylelint to use recommended rule set.

In addition it should be aware of environment in which style will be applied. External plugin looks like a good option to do that. See https://github.com/ismay/stylelint-no-unsupported-browser-features for more details.

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#446](https://github.com/proofit404/cruftbot/issues/446) is still not solved.

**Comment by 0pdd** [comment]
@proofit404 the only puzzle [#446](https://github.com/proofit404/cruftbot/issues/446) is solved here.
