### ISSUE TITLE
Setup gunicorn wsgi server.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#359]
`scripts/serve` should run a real WSGI server instead of Django default run server command.

Reason: it's possible to support SSL connections in it.

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#425](https://github.com/proofit404/cruftbot/issues/425), [#426](https://github.com/proofit404/cruftbot/issues/426) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#425](https://github.com/proofit404/cruftbot/issues/425) is still not solved; solved: [#426](https://github.com/proofit404/cruftbot/issues/426).

**Comment by 0pdd** [comment]
@proofit404 all 2 puzzles are solved here: [#425](https://github.com/proofit404/cruftbot/issues/425), [#426](https://github.com/proofit404/cruftbot/issues/426).
