### ISSUE TITLE
check:33: Setup `eslint-plugin-compat` plugin.

### ISSUE THREAD

**Issue by 0pdd** [proofit404/cruftbot#442]
The puzzle `355-a515b3fb` from #355 has to be resolved: 

https://github.com/proofit404/cruftbot/blob/09b1bd66374aabee443306e61a67959bd187b343/scripts/check#L33-L33

The puzzle was created by @proofit404 on 25-May-21. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `Release 1` from issue #355.

**Comment by proofit404** [comment]
@0crew ticket belongs to #355

**Comment by 0pdd** [comment]
The puzzle `355-a515b3fb` has disappeared from the source code, that's why I closed this issue.
