### ISSUE TITLE
Run pdd locally as part of the CI process.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#46]
#### Requirements:
* docker base image should be plain ubuntu
* install python & ruby in it manually
* run pdd tool as part of [scripts to rule them all](https://github.com/proofit404/cruftbot/issues/44)

(all items above should become puzzles)

**Comment by 0pdd** [comment]
@proofit404 4 puzzles [#95](https://github.com/proofit404/cruftbot/issues/95), [#96](https://github.com/proofit404/cruftbot/issues/96), [#97](https://github.com/proofit404/cruftbot/issues/97), [#98](https://github.com/proofit404/cruftbot/issues/98) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 3 puzzles [#96](https://github.com/proofit404/cruftbot/issues/96), [#97](https://github.com/proofit404/cruftbot/issues/97), [#98](https://github.com/proofit404/cruftbot/issues/98) are still not solved; solved: [#95](https://github.com/proofit404/cruftbot/issues/95).

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#97](https://github.com/proofit404/cruftbot/issues/97), [#98](https://github.com/proofit404/cruftbot/issues/98) are still not solved; solved: [#95](https://github.com/proofit404/cruftbot/issues/95), [#96](https://github.com/proofit404/cruftbot/issues/96).

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#175](https://github.com/proofit404/cruftbot/issues/175), [#97](https://github.com/proofit404/cruftbot/issues/97) are still not solved; solved: [#95](https://github.com/proofit404/cruftbot/issues/95), [#96](https://github.com/proofit404/cruftbot/issues/96), [#98](https://github.com/proofit404/cruftbot/issues/98).

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#175](https://github.com/proofit404/cruftbot/issues/175), [#177](https://github.com/proofit404/cruftbot/issues/177) are still not solved; solved: [#95](https://github.com/proofit404/cruftbot/issues/95), [#96](https://github.com/proofit404/cruftbot/issues/96), [#97](https://github.com/proofit404/cruftbot/issues/97), [#98](https://github.com/proofit404/cruftbot/issues/98).

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#175](https://github.com/proofit404/cruftbot/issues/175) is still not solved; solved: [#177](https://github.com/proofit404/cruftbot/issues/177), [#95](https://github.com/proofit404/cruftbot/issues/95), [#96](https://github.com/proofit404/cruftbot/issues/96), [#97](https://github.com/proofit404/cruftbot/issues/97), [#98](https://github.com/proofit404/cruftbot/issues/98).

**Comment by 0pdd** [comment]
@proofit404 all 6 puzzles are solved here: [#175](https://github.com/proofit404/cruftbot/issues/175), [#177](https://github.com/proofit404/cruftbot/issues/177), [#95](https://github.com/proofit404/cruftbot/issues/95), [#96](https://github.com/proofit404/cruftbot/issues/96), [#97](https://github.com/proofit404/cruftbot/issues/97), [#98](https://github.com/proofit404/cruftbot/issues/98).
