### ISSUE TITLE
Setup docker-compose.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#8]

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#36](https://github.com/proofit404/cruftbot/issues/36), [#37](https://github.com/proofit404/cruftbot/issues/37) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#37](https://github.com/proofit404/cruftbot/issues/37) is still not solved; solved: [#36](https://github.com/proofit404/cruftbot/issues/36).

**Comment by 0pdd** [comment]
@proofit404 all 2 puzzles are solved here: [#36](https://github.com/proofit404/cruftbot/issues/36), [#37](https://github.com/proofit404/cruftbot/issues/37).
