### ISSUE TITLE
Setup Danger.

### ISSUE THREAD

**Issue by proofit404** [proofit404/cruftbot#92]

**Comment by 0pdd** [comment]
@proofit404 12 puzzles [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#131](https://github.com/proofit404/cruftbot/issues/131), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 13 puzzles [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#131](https://github.com/proofit404/cruftbot/issues/131), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 12 puzzles [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#131](https://github.com/proofit404/cruftbot/issues/131), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133) are still not solved; solved: [#160](https://github.com/proofit404/cruftbot/issues/160).

**Comment by 0pdd** [comment]
@proofit404 11 puzzles [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#131](https://github.com/proofit404/cruftbot/issues/131), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#160](https://github.com/proofit404/cruftbot/issues/160).

**Comment by 0pdd** [comment]
@proofit404 10 puzzles [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#131](https://github.com/proofit404/cruftbot/issues/131), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#125](https://github.com/proofit404/cruftbot/issues/125), [#160](https://github.com/proofit404/cruftbot/issues/160).

**Comment by 0pdd** [comment]
@proofit404 9 puzzles [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#131](https://github.com/proofit404/cruftbot/issues/131), [#133](https://github.com/proofit404/cruftbot/issues/133) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#125](https://github.com/proofit404/cruftbot/issues/125), [#132](https://github.com/proofit404/cruftbot/issues/132), [#160](https://github.com/proofit404/cruftbot/issues/160).

**Comment by 0pdd** [comment]
@proofit404 8 puzzles [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#131](https://github.com/proofit404/cruftbot/issues/131), [#133](https://github.com/proofit404/cruftbot/issues/133) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#125](https://github.com/proofit404/cruftbot/issues/125), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#160](https://github.com/proofit404/cruftbot/issues/160).

**Comment by 0pdd** [comment]
@proofit404 7 puzzles [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#131](https://github.com/proofit404/cruftbot/issues/131) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#125](https://github.com/proofit404/cruftbot/issues/125), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160).

**Comment by 0pdd** [comment]
@proofit404 6 puzzles [#124](https://github.com/proofit404/cruftbot/issues/124), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#131](https://github.com/proofit404/cruftbot/issues/131) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#125](https://github.com/proofit404/cruftbot/issues/125), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160).

**Comment by 0pdd** [comment]
@proofit404 8 puzzles [#124](https://github.com/proofit404/cruftbot/issues/124), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#131](https://github.com/proofit404/cruftbot/issues/131), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#125](https://github.com/proofit404/cruftbot/issues/125), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160).

**Comment by 0pdd** [comment]
@proofit404 7 puzzles [#124](https://github.com/proofit404/cruftbot/issues/124), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#131](https://github.com/proofit404/cruftbot/issues/131), [#280](https://github.com/proofit404/cruftbot/issues/280) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#125](https://github.com/proofit404/cruftbot/issues/125), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279).

**Comment by 0pdd** [comment]
@proofit404 5 puzzles [#124](https://github.com/proofit404/cruftbot/issues/124), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#131](https://github.com/proofit404/cruftbot/issues/131) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280).

**Comment by 0pdd** [comment]
@proofit404 4 puzzles [#124](https://github.com/proofit404/cruftbot/issues/124), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#131](https://github.com/proofit404/cruftbot/issues/131) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280).

**Comment by 0pdd** [comment]
@proofit404 5 puzzles [#124](https://github.com/proofit404/cruftbot/issues/124), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#131](https://github.com/proofit404/cruftbot/issues/131), [#292](https://github.com/proofit404/cruftbot/issues/292) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280).

**Comment by 0pdd** [comment]
@proofit404 4 puzzles [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#131](https://github.com/proofit404/cruftbot/issues/131), [#292](https://github.com/proofit404/cruftbot/issues/292) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280).

**Comment by 0pdd** [comment]
@proofit404 3 puzzles [#128](https://github.com/proofit404/cruftbot/issues/128), [#131](https://github.com/proofit404/cruftbot/issues/131), [#292](https://github.com/proofit404/cruftbot/issues/292) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280).

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#131](https://github.com/proofit404/cruftbot/issues/131), [#292](https://github.com/proofit404/cruftbot/issues/292) are still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280).

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#292](https://github.com/proofit404/cruftbot/issues/292) is still not solved; solved: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#131](https://github.com/proofit404/cruftbot/issues/131), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280).

**Comment by 0pdd** [comment]
@proofit404 all 16 puzzles are solved here: [#122](https://github.com/proofit404/cruftbot/issues/122), [#123](https://github.com/proofit404/cruftbot/issues/123), [#124](https://github.com/proofit404/cruftbot/issues/124), [#125](https://github.com/proofit404/cruftbot/issues/125), [#126](https://github.com/proofit404/cruftbot/issues/126), [#127](https://github.com/proofit404/cruftbot/issues/127), [#128](https://github.com/proofit404/cruftbot/issues/128), [#129](https://github.com/proofit404/cruftbot/issues/129), [#130](https://github.com/proofit404/cruftbot/issues/130), [#131](https://github.com/proofit404/cruftbot/issues/131), [#132](https://github.com/proofit404/cruftbot/issues/132), [#133](https://github.com/proofit404/cruftbot/issues/133), [#160](https://github.com/proofit404/cruftbot/issues/160), [#279](https://github.com/proofit404/cruftbot/issues/279), [#280](https://github.com/proofit404/cruftbot/issues/280), [#292](https://github.com/proofit404/cruftbot/issues/292).
